__include__: ['./rtdetrv2_r18vd_itobos.yml']

# Eval on the TEST split (used with --test-only)
val_dataloader:
  dataset:
    img_folder: /scratch2/lesion_detection/split_dataset_blurred/test/images
    ann_file:   /scratch2/lesion_detection/split_dataset_blurred/annotations/test.json
